version: '3'
# postgresを起こす
services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./tmp/db:/var/lib/postgresql/data 
    environment: 
      POSTGRES_PASSWORD: 'postgres'

  # rails sを実行
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ".:/myapp"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379
    tty: true
    stdin_open: true

  redis:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - api-redis:/var/lib/redis/data
      
volumes:
  api-redis: